---
title: "FAoptions"
output:
  word_document: null
  keep_md: yes
---


```{r load packages, warning = FALSE, message = FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(tsibble))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(psych))
library(officer)
library(magrittr)

```



```{r, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
moduletwo <- read_excel(here::here("thesis_surveydata/political_factors_complete.xlsx"))
save(moduletwo, file = "moduletwo.rda")
module2 <- data.frame(moduletwo)
module2[module2 == "Rather not say/ Don't know"] <- "Rather not say/Don't know"
#module2 %>% filter(!row_number() %in% c(1,2))

# loaded data set for module 2 eco -pol variables and removes the rows with question number and question text
```


```{r, eval =TRUE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
#This chunk contains the coding schemes of various scales used in survey one: eco-political factors, kahan scale and acceptance scale
codedmodule2 <- module2 %>%
  
#remove row 1
  filter(!row_number() %in% c(1,2)) %>% 
  
# replace risky likert scale with numbers
  mutate_at(vars(starts_with("Risky")), funs(case_when(. =="Not at all risky" ~ 1, 
                                                       . =="Slightly risky" ~ 2, 
                                                       . =="Moderately risky" ~ 3, 
                                                       . =="Very risky" ~ 4, 
                                                       . =="Extremely risky" ~ 5))) %>%

# replace beneficial likert scale with numbers  
  mutate_at(vars(starts_with("Ben")), funs(case_when(. =="Not at all beneficial" ~ 1,
                                                     . =="Slightly beneficial" ~ 2,
                                                     . =="Moderately beneficial" ~ 3,
                                                     . =="Very beneficial" ~ 4,
                                                     . =="Extremely beneficial" ~ 5 ))) %>%

# replace nuclear acceptance likert scale with numbers
  mutate_at(vars(N_accept,N_reluctantlyaccept,N_reject), funs(case_when(. == "Strongly disagree" ~ 1, 
                                                                        . == "Somewhat disagree" ~ 2,
                                                                        . == "Neither agree nor disagree" ~3,
                                                                        . == "Somewhat agree" ~ 4,
                                                                        . == "Strongly agree" ~ 5))) %>%
  
# code likert scale for variables for Kahan scale into numbers
  mutate_at(vars(starts_with (c("K_I","K_H","DISPLACE", "POLLUTE", "HEALTH", "JOBS", "BEAUTY", "PRIDE", "NPRIDE", "DEV", "PROSPER", "RELY"))), funs(case_when(. == "Strongly disagree" ~ 1, 
               . == "Somewhat disagree" ~ 2,
               . == "Neither agree nor disagree" ~3,
               . == "Somewhat agree" ~ 4,
               . == "Strongly agree" ~ 5))) %>%
  
# reverse code for likert scale for variables for Kahan scale into numbers
mutate_at(vars(starts_with (c("K_S","K_E"))), funs(case_when(. == "Strongly disagree" ~ 5, 
                                                               . == "Somewhat disagree" ~ 4,
                                                               . == "Neither agree nor disagree" ~3,
                                                               . == "Somewhat agree" ~ 2,
                                                               . == "Strongly agree" ~ 1))) %>%

# code eco-pol scale variables into numbers
  mutate_at(vars(SYSTEMDEMO,SYSTEMRELIGION,SYSTEMTECHNO,SYSTEMTOTAL,WEALTHLIM,MECHANISATION,DECISIONDECEN,INDUSTRYSMALL,ECONOMYLOCAL,ENVOVERDEV,OWNERPUB, OWNERREG), funs(case_when(. == "Strongly disagree" ~ 1, 
                        . == "Somewhat disagree" ~ 2,
                        . == "Neither agree nor disagree" ~3,
                        . == "Somewhat agree" ~ 4,
                        . == "Strongly agree" ~ 5))) %>%

# reverse code eco-pol scale variables into numbers 
 mutate_at(vars(DECISIONCEN,INDUSTRYLARGE,ECONOMYGLOBAL,OWNERPVT,OWNERNOREG), funs(case_when(. == "Strongly disagree" ~ 5, 
                                                                                                         . == "Somewhat disagree" ~ 4,
                                                                                                         . == "Neither agree nor disagree" ~3,
                                                                                                         . == "Somewhat agree" ~ 2,
                                                                                                         . == "Strongly agree" ~ 1)))
```


# Two factor solution is slightly different for Nuclear, Solar and Coal. 


## Nuclear 

```{r, echo=FALSE}

library(psych)
library(tidyverse)


fascales <- codedmodule2 %>%
  dplyr::select(starts_with(c("K_","Risky_Nuclear","WEALTHLIM","MECHANISATION","DECISIONDECEN","DECISIONCEN","INDUSTRYLARGE","INDUSTRYSMALL","ECONOMYGLOBAL","ECONOMYLOCAL", "ENVOVERDEV","DEVOVERENV","OWNERPVT","OWNERNOREG","OWNERPUB", "OWNERREG","DISPLACENUCLEAR",  "POLLUTENUCLEAR", "HEALTHNUCLEAR", "JOBSNUCLEAR", "BEAUTYNUCLEAR", "PRIDENUCLEAR", "NPRIDENUCLEAR", "DEVNUCLEAR", "PROSPERNUCLEAR", "RELYNUCLEAR", "Uppercaste", "Male", "Hindu", "Urban", "State","age")))%>%
  mutate_at(vars(age), funs(case_when(. == "18-24 years old" ~ 1, 
                                      . == "25-34 years old" ~ 2,
                                      . ==  "35-44 years old" ~3,
                                      . == "45-54 years old" ~ 4,
                                      . == "55-64 years old" ~ 5,
                                      . == "65-74 years old" ~ 6,
                                      . == "75 years or older" ~ 7))) %>%
  na.omit()
ecopolall <- fascales %>%
        dplyr::select("WEALTHLIM","MECHANISATION","DECISIONDECEN","DECISIONCEN","INDUSTRYLARGE","INDUSTRYSMALL","ECONOMYGLOBAL","ECONOMYLOCAL", "ENVOVERDEV","DEVOVERENV","OWNERPVT","OWNERNOREG","OWNERPUB", "OWNERREG","DISPLACENUCLEAR",  "POLLUTENUCLEAR", "HEALTHNUCLEAR", "JOBSNUCLEAR", "BEAUTYNUCLEAR", "PRIDENUCLEAR", "NPRIDENUCLEAR", "DEVNUCLEAR", "PROSPERNUCLEAR", "RELYNUCLEAR")%>%
    rename(
      "Limits on Wealth " = "WEALTHLIM",
      "Anti Mechanisation of work" = "MECHANISATION",
      "Pro Decentralisation" = "DECISIONDECEN",
      "Pro Centralisation" = "DECISIONCEN",
      "Pro Large Industries" = "INDUSTRYLARGE",
      "Anti Large Industries " = "INDUSTRYSMALL",
      "Pro Globaleconomy" = "ECONOMYGLOBAL",
      "Pro Localeconomy" = "ECONOMYLOCAL",
      "Environment over Development" = "ENVOVERDEV",
      "Development over Environment" = "DEVOVERENV",
      "Pro Private ownership " = "OWNERPVT",
      "Anti Regulations" = "OWNERNOREG",
      "Pro Public ownership" = "OWNERPUB",
      "Pro Regulations" = "OWNERREG",
      "Displacement risk(nuclear)" = "DISPLACENUCLEAR",
      "Pollution risk(nuclear) " = "POLLUTENUCLEAR",
      "Health risk(nuclear)" = "HEALTHNUCLEAR",
      "Job opportunities(nuclear)" = "JOBSNUCLEAR",
      "Spoils Natural Beauty(nuclear)" = "BEAUTYNUCLEAR",
      "Community pride(nuclear)" = "PRIDENUCLEAR",
      "National pride(nuclear)" = "NPRIDENUCLEAR",
      "National development(nuclear)" = "DEVNUCLEAR",
      "Local prosperity(nuclear)" = "PROSPERNUCLEAR",
      "Reliance on government(nuclear)" = "RELYNUCLEAR"
    )


ecopolall2.fa <- fa(ecopolall, nfactors = 2, rotate = "varimax")


```


```{r, echo=FALSE}

library(flextable)

set_flextable_defaults(docx.landscape = TRUE)

flex <- function(data, title=NULL) {
  # this grabs the data and converts it to a flextbale
  flextable(data) %>%
  # this makes the table fill the page width
  set_table_properties(layout = "autofit", width = 1) %>%
  # font size
  fontsize(size=10, part="all") %>%
    #this adds a ttitlecreates an automatic table number
      set_caption(title, 
                  autonum = officer::run_autonum(seq_id = "tab", 
                                                 pre_label = "Table ", 
                                                 post_label = "\n", 
                                                 bkm = "anytable")) #%>%
  # font type
  #font(fontname="Times New Roman", part="all")
}

rename_map <- c(
  "Limits on Wealth" = "A limit should be put to how much wealth a person can amass",
  "Anti Mechanisation of work" = "Rapid mechanization of work is taking away jobs from workers in this country",
  "Pro Decentralisation" = "Local politicians shouldn't have to ask permission from the central government to implement policies",
  "Pro Centralisation" = "Laws and policies would be implemented more smoothly if more power lay with the central government",
  "Pro Large Industries" = "Large scale industries are required for the development of the country that will benefit everyone",
  "Anti Large Industries" = "Large corporations are destroying the local industries in India and benefiting only a handful of people",
  "Pro Globaleconomy" = "Foreign companies have led to a range of benefits for the Indian people and society",
  "Pro Localeconomy" = "India would be better off if foreign companies didn't come to here",
  "Environment over Development" = "Polluting industries that spoil the environment should be shut down even if it costs people their jobs",
  "Development over Environment" = "Economic growth and creating jobs should be prioritized over environmental protection",
  "Pro Private ownership" = "All businesses and industries should be owned privately",
  "Anti Regulations" = "There is too much red-tape and the government should not interfere with businesses and industries",
  "Pro Public ownership" = "The government should own most large businesses and industries",
  "Pro Regulations" = " Regardless of ownership, the government should pass strong regulations and implement them",
  "Displacement risk(nuclear)" = "Nuclear energy is leading to displacement of people from their land",
  "Spoils Natural Beauty(nuclear)" = "Nuclear energy spoils the natural beauty of the landscape",
  "Pollution risk(nuclear)" = "Nuclear energy increases pollution of air/water/land",
  "Health risk(nuclear)" = "Nuclear energy poses a great risk to the health of people living around it",
  "Job opportunities(nuclear)" = "Nuclear energy will bring jobs to the local community",
  "Community pride(nuclear)" = "I would be proud if my community used nuclear energy",
  "National pride(nuclear)" = "Nuclear energy is a mark of pride for our nation",
  "National development(nuclear)" = "Nuclear energy pushes forward the country's development",
  "Local prosperity(nuclear)" = "Nuclear energy brings economic prosperity to the surrounding regions",
  "Reliance on government(nuclear)" = "I don't like the idea that I have to rely on the government for electricity from nuclear energy"
)


fa_table <- function(x, cut) {
  #get sorted loadings
  loadings <- fa.sort(x)$loadings %>% round(3)
  #suppress loadings
  loadings[loadings > -cut & loadings < cut] <- ""
  #get additional info  
  add_info <- cbind(x$communalities, 
                    x$uniquenesses,
                    x$complexity) %>%
    # make it a data frame
    as.data.frame() %>%
    # column names
    rename("Communality" = V1,
           "Uniqueness" = V2,
           "Complexity" = V3) %>%
    #get the item names from the vector
    rownames_to_column("item")
  
  #build table
  loadings %>%
    unclass() %>%
    as.data.frame() %>%
    rownames_to_column("item") %>%
    left_join(add_info) %>%
    mutate(
      item = if_else(item %in% names(rename_map), rename_map[item], item),
      code = names(rename_map)[match(item, rename_map)], # extracting short form
      across(where(is.numeric), round, 3)
    ) %>%
    select(code, everything()) # reorder columns to bring code to the front
}

fa_table(ecopolall2.fa, .4) %>%
  rename(Pdevelop = MR1, Ndevelop = MR2, Items= item) %>%
  flex("2 factor solution") %>%
  autofit()


```



```{r, echo = FALSE}
ecopolall2.fa[["Vaccounted"]] %>%
  as.data.frame() %>%
  rownames_to_column("Property") %>%
  rename(Pdevelop = MR1, Ndevelop = MR2) %>%
    mutate(across(where(is.numeric), round, 3)) %>%
    flex("Eigenvalues and Variance Explained for 2 Factor Solution")
```



\newpage
## Solar

```{r, echo=FALSE}
library(psych)
library(tidyverse)

sfascales <- codedmodule2 %>%
  dplyr::select(starts_with(c("K_","Risky_Solar","WEALTHLIM","MECHANISATION","DECISIONDECEN","DECISIONCEN","INDUSTRYLARGE","INDUSTRYSMALL","ECONOMYGLOBAL","ECONOMYLOCAL", "ENVOVERDEV","DEVOVERENV","OWNERPVT","OWNERNOREG","OWNERPUB", "OWNERREG","DISPLACESOLAR", "POLLUTESOLAR", "HEALTHSOLAR", "JOBSSOLAR", "BEAUTYSOLAR", "PRIDESOLAR", "NPRIDESOLAR", "DEVSOLAR", "PROSPERSOLAR", "RELYSOLAR", "Uppercaste", "Male", "Hindu", "Urban", "State","age")))%>%
  mutate_at(vars(age), funs(case_when(. == "18-24 years old" ~ 1, 
                                      . == "25-34 years old" ~ 2,
                                      . ==  "35-44 years old" ~3,
                                      . == "45-54 years old" ~ 4,
                                      . == "55-64 years old" ~ 5,
                                      . == "65-74 years old" ~ 6,
                                      . == "75 years or older" ~ 7))) %>%
  na.omit()

secopolall <- sfascales %>%
        dplyr::select("WEALTHLIM","MECHANISATION","DECISIONDECEN","DECISIONCEN","INDUSTRYLARGE","INDUSTRYSMALL","ECONOMYGLOBAL","ECONOMYLOCAL", "ENVOVERDEV","DEVOVERENV","OWNERPVT","OWNERNOREG","OWNERPUB", "OWNERREG","DISPLACESOLAR", "POLLUTESOLAR", "HEALTHSOLAR", "JOBSSOLAR", "BEAUTYSOLAR", "PRIDESOLAR", "NPRIDESOLAR", "DEVSOLAR", "PROSPERSOLAR", "RELYSOLAR")%>%
    rename(
      "Limits on Wealth " = "WEALTHLIM",
      "Anti Mechanisation of work" = "MECHANISATION",
      "Pro Decentralisation" = "DECISIONDECEN",
      "Pro Centralisation" = "DECISIONCEN",
      "Pro Large Industries" = "INDUSTRYLARGE",
      "Anti Large Industries " = "INDUSTRYSMALL",
      "Pro Globaleconomy" = "ECONOMYGLOBAL",
      "Pro Localeconomy" = "ECONOMYLOCAL",
      "Environment over Development" = "ENVOVERDEV",
      "Development over Environment" = "DEVOVERENV",
      "Pro Private ownership " = "OWNERPVT",
      "Anti Regulations" = "OWNERNOREG",
      "Pro Public ownership" = "OWNERPUB",
      "Pro Regulations" = "OWNERREG",
      "Displacement risk(solar)" = "DISPLACESOLAR",
      "Pollution risk(solar) " = "POLLUTESOLAR",
      "Health risk(solar)" = "HEALTHSOLAR",
      "Job opportunities(solar)" = "JOBSSOLAR",
      "Spoils Natural Beauty(solar)" = "BEAUTYSOLAR",
      "Community pride(solar)" = "PRIDESOLAR",
      "National pride(solar)" = "NPRIDESOLAR",
      "National development(solar)" = "DEVSOLAR",
      "Local prosperity(solar)" = "PROSPERSOLAR",
      "Reliance on government(solar)" = "RELYSOLAR"
    )

secopolall2.fa <- fa(secopolall, nfactors = 2, rotate = "varimax")


```



```{r, echo=FALSE}

library(flextable)

set_flextable_defaults(docx.landscape = TRUE)

flex <- function(data, title=NULL) {
  # this grabs the data and converts it to a flextbale
  flextable(data) %>%
  # this makes the table fill the page width
  set_table_properties(layout = "autofit", width = 1) %>%
  # font size
  fontsize(size=10, part="all") %>%
    #this adds a ttitlecreates an automatic table number
      set_caption(title, 
                  autonum = officer::run_autonum(seq_id = "tab", 
                                                 pre_label = "Table ", 
                                                 post_label = "\n", 
                                                 bkm = "anytable")) #%>%
  # font type
  #font(fontname="Times New Roman", part="all")
}

srename_map <- c(
  "Limits on Wealth" = "A limit should be put to how much wealth a person can amass",
  "Anti Mechanisation of work" = "Rapid mechanization of work is taking away jobs from workers in this country",
  "Pro Decentralisation" = "Local politicians shouldn't have to ask permission from the central government to implement policies",
  "Pro Centralisation" = "Laws and policies would be implemented more smoothly if more power lay with the central government",
  "Pro Large Industries" = "Large scale industries are required for the development of the country that will benefit everyone",
  "Anti Large Industries" = "Large corporations are destroying the local industries in India and benefiting only a handful of people",
  "Pro Globaleconomy" = "Foreign companies have led to a range of benefits for the Indian people and society",
  "Pro Localeconomy" = "India would be better off if foreign companies didn't come to here",
  "Environment over Development" = "Polluting industries that spoil the environment should be shut down even if it costs people their jobs",
  "Development over Environment" = "Economic growth and creating jobs should be prioritized over environmental protection",
  "Pro Private ownership" = "All businesses and industries should be owned privately",
  "Anti Regulations" = "There is too much red-tape and the government should not interfere with businesses and industries",
  "Pro Public ownership" = "The government should own most large businesses and industries",
  "Pro Regulations" = "Regardless of ownership, the government should pass strong regulations and implement them",
  "Displacement risk(solar)" = "Solar energy is leading to displacement of people from their land",
  "Spoils Natural Beauty(solar)" = "Solar energy spoils the natural beauty of the landscape",
  "Pollution risk(solar)" = "Solar energy increases pollution of air/water/land",
  "Health risk(solar)" = "Solar energy poses a great risk to the health of people living around it",
  "Job opportunities(solar)" = "Solar energy will bring jobs to the local community",
  "Community pride(solar)" = "I would be proud if my community used solar energy",
  "National pride(solar)" = "Solar energy is a mark of pride for our nation",
  "National development(solar)" = "Solar energy pushes forward the country's development",
  "Local prosperity(solar)" = "Solar energy brings economic prosperity to the surrounding regions",
  "Reliance on government(solar)" = "I don't like the idea that I have to rely on the government for electricity from solar energy"
)


fa_table <- function(x, cut) {
  #get sorted loadings
  loadings <- fa.sort(x)$loadings %>% round(3)
  #suppress loadings
  loadings[loadings > -cut & loadings < cut] <- ""
  #get additional info  
  add_info <- cbind(x$communalities, 
                    x$uniquenesses,
                    x$complexity) %>%
    # make it a data frame
    as.data.frame() %>%
    # column names
    rename("Communality" = V1,
           "Uniqueness" = V2,
           "Complexity" = V3) %>%
    #get the item names from the vector
    rownames_to_column("item")
  
  #build table
  loadings %>%
    unclass() %>%
    as.data.frame() %>%
    rownames_to_column("item") %>%
    left_join(add_info) %>%
    mutate(
      item = if_else(item %in% names(srename_map), srename_map[item], item),
      code = names(srename_map)[match(item, srename_map)], # extracting short form
      across(where(is.numeric), round, 3)
    ) %>%
    select(code, everything()) # reorder columns to bring code to the front
}

fa_table(secopolall2.fa, .4) %>%
  #rename(Pdevelop = MR1, Ndevelop = MR2, Items= item) %>%
  flex("2 factor solution") %>%
  autofit()


```



```{r, echo = FALSE}
secopolall2.fa[["Vaccounted"]] %>%
  as.data.frame() %>%
  rownames_to_column("Property") %>%
  #rename(Pdevelop = MR1, Ndevelop = MR2) %>%
    mutate(across(where(is.numeric), round, 3)) %>%
    flex("Solar: Eigenvalues and Variance Explained for 2 Factor Solution")
```

\newpage
## Coal 

```{r, echo = FALSE}

cecopolall <- codedmodule2 %>%
        dplyr::select("WEALTHLIM","MECHANISATION","DECISIONDECEN","DECISIONCEN","INDUSTRYLARGE","INDUSTRYSMALL","ECONOMYGLOBAL","ECONOMYLOCAL", "ENVOVERDEV","DEVOVERENV","OWNERPVT","OWNERNOREG","OWNERPUB", "OWNERREG","DISPLACECOAL", "POLLUTECOAL", "HEALTHCOAL", "JOBSCOAL", "BEAUTYCOAL", "PRIDECOAL", "NPRIDECOAL", "DEVCOAL", "PROSPERCOAL", "RELYCOAL")%>%
      rename(
      "Limits on Wealth " = "WEALTHLIM",
      "Anti Mechanisation of work" = "MECHANISATION",
      "Pro Decentralisation" = "DECISIONDECEN",
      "Pro Centralisation" = "DECISIONCEN",
      "Pro Large Industries" = "INDUSTRYLARGE",
      "Anti Large Industries " = "INDUSTRYSMALL",
      "Pro Globaleconomy" = "ECONOMYGLOBAL",
      "Pro Localeconomy" = "ECONOMYLOCAL",
      "Environment over Development" = "ENVOVERDEV",
      "Development over Environment" = "DEVOVERENV",
      "Pro Private ownership " = "OWNERPVT",
      "Anti Regulations" = "OWNERNOREG",
      "Pro Public ownership" = "OWNERPUB",
      "Pro Regulations" = "OWNERREG",
      "Displacement risk(coal)" = "DISPLACECOAL",
      "Pollution risk(coal) " = "POLLUTECOAL",
      "Health risk(coal)" = "HEALTHCOAL",
      "Job opportunities(coal)" = "JOBSCOAL",
      "Spoils Natural Beauty(coal)" = "BEAUTYCOAL",
      "Community pride(coal)" = "PRIDECOAL",
      "National pride(coal)" = "NPRIDECOAL",
      "National development(coal)" = "DEVCOAL",
      "Local prosperity(coal)" = "PROSPERCOAL",
      "Reliance on government(coal)" = "RELYCOAL"
    )%>%
  na.omit()


cecopolall2.fa <- fa(cecopolall, nfactors = 2, rotate = "varimax")



```



```{r, echo=FALSE}

library(flextable)

set_flextable_defaults(docx.landscape = TRUE)

flex <- function(data, title=NULL) {
  # this grabs the data and converts it to a flextbale
  flextable(data) %>%
  # this makes the table fill the page width
  set_table_properties(layout = "autofit", width = 1) %>%
  # font size
  fontsize(size=10, part="all") %>%
    #this adds a ttitlecreates an automatic table number
      set_caption(title, 
                  autonum = officer::run_autonum(seq_id = "tab", 
                                                 pre_label = "Table ", 
                                                 post_label = "\n", 
                                                 bkm = "anytable")) #%>%
  # font type
  #font(fontname="Times New Roman", part="all")
}

crename_map <- c(
  "Limits on Wealth" = "A limit should be put to how much wealth a person can amass",
  "Anti Mechanisation of work" = "Rapid mechanization of work is taking away jobs from workers in this country",
  "Pro Decentralisation" = "Local politicians shouldn't have to ask permission from the central government to implement policies",
  "Pro Centralisation" = "Laws and policies would be implemented more smoothly if more power lay with the central government",
  "Pro Large Industries" = "Large scale industries are required for the development of the country that will benefit everyone",
  "Anti Large Industries" = "Large corporations are destroying the local industries in India and benefiting only a handful of people",
  "Pro Globaleconomy" = "Foreign companies have led to a range of benefits for the Indian people and society",
  "Pro Localeconomy" = "India would be better off if foreign companies didn't come to here",
  "Environment over Development" = "Polluting industries that spoil the environment should be shut down even if it costs people their jobs",
  "Development over Environment" = "Economic growth and creating jobs should be prioritized over environmental protection",
  "Pro Private ownership" = "All businesses and industries should be owned privately",
  "Anti Regulations" = "There is too much red-tape and the government should not interfere with businesses and industries",
  "Pro Public ownership" = "The government should own most large businesses and industries",
  "Pro Regulations" = "Regardless of ownership, the government should pass strong regulations and implement them",
  "Displacement risk(coal)" = "Coal powered plants are leading to displacement of people from their land",
  "Spoils Natural Beauty(coal)" = "Coal powered plants spoil the natural beauty of the landscape",
  "Pollution risk(coal)" = "Coal powered plants increase pollution of air/water/land",
  "Health risk(coal)" = "Coal powered plants pose a great risk to the health of people living around it",
  "Job opportunities(coal)" = "Coal powered plants will bring jobs to the local community",
  "Community pride(coal)" = "I would be proud if my community used coal powered plants",
  "National pride(coal)" = "Coal powered plants are a mark of pride for our nation",
  "National development(coal)" = "Coal powered plants push forward the country's development",
  "Local prosperity(coal)" = "Coal powered plants bring economic prosperity to the surrounding regions",
  "Reliance on government(coal)" = "I don't like the idea that I have to rely on the government for electricity from coal powered plants"
)


fa_table <- function(x, cut) {
  #get sorted loadings
  loadings <- fa.sort(x)$loadings %>% round(3)
  #suppress loadings
  loadings[loadings > -cut & loadings < cut] <- ""
  #get additional info  
  add_info <- cbind(x$communalities, 
                    x$uniquenesses,
                    x$complexity) %>%
    # make it a data frame
    as.data.frame() %>%
    # column names
    rename("Communality" = V1,
           "Uniqueness" = V2,
           "Complexity" = V3) %>%
    #get the item names from the vector
    rownames_to_column("item")
  
  #build table
  loadings %>%
    unclass() %>%
    as.data.frame() %>%
    rownames_to_column("item") %>%
    left_join(add_info) %>%
    mutate(
      item = if_else(item %in% names(crename_map), crename_map[item], item),
      code = names(crename_map)[match(item, crename_map)], # extracting short form
      across(where(is.numeric), round, 3)
    ) %>%
    select(code, everything()) # reorder columns to bring code to the front
}

fa_table(cecopolall2.fa, .4) %>%
  #rename(Pdevelop = MR1, Ndevelop = MR2, Items= item) %>%
  flex("2 factor solution") %>%
  autofit()


```




```{r, echo = FALSE}
cecopolall2.fa[["Vaccounted"]] %>%
  as.data.frame() %>%
  rownames_to_column("Property") %>%
  #rename(Pdevelop = MR1, Ndevelop = MR2) %>%
    mutate(across(where(is.numeric), round, 3)) %>%
    flex("Coal: Eigenvalues and Variance Explained for 2 Factor Solution")
```




\newpage
# Alternative Solution :  FA on Two Separate scales 

## Scale 1: Factor analysis on Eco-political values of the perceiver scale
 4 factor solution 

```{r, echo = FALSE}

# below are only eco-pol values of the perceiver scale. 

ecopolval <- codedmodule2 %>%
        dplyr::select("WEALTHLIM","MECHANISATION","INDUSTRYSMALL","ECONOMYGLOBAL", "ENVOVERDEV","OWNERNOREG","OWNERPUB", "OWNERREG", "DECISIONDECEN","DECISIONCEN","INDUSTRYLARGE","ECONOMYLOCAL", "DEVOVERENV","OWNERPVT")%>%
  na.omit() %>%
    rename(
      "Limits on Wealth" = "WEALTHLIM",
      "Anti Mechanisation of work" = "MECHANISATION",
      "Pro Decentralisation" = "DECISIONDECEN",
      "Pro Centralisation" = "DECISIONCEN",
      "Pro Large Industries" = "INDUSTRYLARGE",
      "Anti Large Industries " = "INDUSTRYSMALL",
      "Pro Globaleconomy" = "ECONOMYGLOBAL",
      "Pro Localeconomy" = "ECONOMYLOCAL",
      "Environment over Development" = "ENVOVERDEV",
      "Development over Environment" = "DEVOVERENV",
      "Pro Private ownership " = "OWNERPVT",
      "Anti Regulations" = "OWNERNOREG",
      "Pro Public ownership" = "OWNERPUB",
      "Pro Regulations" = "OWNERREG"
    )

#alpha(ecopolval, check.keys = TRUE) # 0.71

#ncol(ecopolval)  number of cols is 14 

#ecopolval_cor <- cor(ecopolval)
#PCA14 <- principal(ecopolval, nfactors = 14, rotate = "none") # no rotation to start with. 

#print(PCA14)

#PCA14$loadings

#fa.parallel(ecopolval_cor)

ecopolval4.fa <- fa(ecopolval, nfactors = 4, rotate = "varimax")

#cor(ecopolval)

# questions for Terre , 2) 4 factors/3 factors/2 factors - variation explained how should i deal with that. 
# four factor analysis - MR1 - problems of industrialisation MR2 - local economy and decision making MR3 - centralised and large industry MR4- dev/ownership
```




```{r, echo=FALSE}

library(flextable)

set_flextable_defaults(docx.landscape = TRUE)

flex <- function(data, title=NULL) {
  # this grabs the data and converts it to a flextbale
  flextable(data) %>%
  # this makes the table fill the page width
  set_table_properties(layout = "autofit", width = 1) %>%
  # font size
  fontsize(size=10, part="all") %>%
    #this adds a ttitlecreates an automatic table number
      set_caption(title, 
                  autonum = officer::run_autonum(seq_id = "tab", 
                                                 pre_label = "Table ", 
                                                 post_label = "\n", 
                                                 bkm = "anytable")) #%>%
  # font type
  #font(fontname="Times New Roman", part="all")
}

rename_map <- c(
  "Limits on Wealth" = "A limit should be put to how much wealth a person can amass",
  "Anti Mechanisation of work" = "Rapid mechanization of work is taking away jobs from workers in this country",
  "Pro Decentralisation" = "Local politicians shouldn't have to ask permission from the central government to implement policies",
  "Pro Centralisation" = "Laws and policies would be implemented more smoothly if more power lay with the central government",
  "Pro Large Industries" = "Large scale industries are required for the development of the country that will benefit everyone",
  "Anti Large Industries" = "Large corporations are destroying the local industries in India and benefiting only a handful of people",
  "Pro Globaleconomy" = "Foreign companies have led to a range of benefits for the Indian people and society",
  "Pro Localeconomy" = "India would be better off if foreign companies didn't come to here",
  "Environment over Development" = "Polluting industries that spoil the environment should be shut down even if it costs people their jobs",
  "Development over Environment" = "Economic growth and creating jobs should be prioritized over environmental protection",
  "Pro Private ownership" = "All businesses and industries should be owned privately",
  "Anti Regulations" = "There is too much red-tape and the government should not interfere with businesses and industries",
  "Pro Public ownership" = "The government should own most large businesses and industries",
  "Pro Regulations" = " Regardless of ownership, the government should pass strong regulations and implement them"
)

fa_table <- function(x, cut) {
  #get sorted loadings
  loadings <- fa.sort(x)$loadings %>% round(3)
  #suppress loadings
  loadings[loadings > -cut & loadings < cut] <- ""
  #get additional info  
  add_info <- cbind(x$communalities, 
                    x$uniquenesses,
                    x$complexity) %>%
    # make it a data frame
    as.data.frame() %>%
    # column names
    rename("Communality" = V1,
           "Uniqueness" = V2,
           "Complexity" = V3) %>%
    #get the item names from the vector
    rownames_to_column("item")
  
  #build table
  loadings %>%
    unclass() %>%
    as.data.frame() %>%
    rownames_to_column("item") %>%
    left_join(add_info) %>%
    mutate(
      item = if_else(item %in% names(rename_map), rename_map[item], item),
      code = names(rename_map)[match(item, rename_map)], # extracting short form
      across(where(is.numeric), round, 3)
    ) %>%
    select(code, everything()) # reorder columns to bring code to the front
}

fa_table(ecopolval4.fa, .4) %>%
  #rename(Pdevelop = MR1, Ndevelop = MR2, Items= item) %>%
  flex("4 factor solution same for all technologies") %>%
  autofit()


```



```{r, echo=FALSE}

library(flextable)


flex <- function(data, title=NULL) {
  # this grabs the data and converts it to a flextbale
  flextable(data) %>%
  # this makes the table fill the page width
  set_table_properties(layout = "autofit", width = 1) %>%
  # font size
  fontsize(size=10, part="all") %>%
    #this adds a ttitlecreates an automatic table number
      set_caption(title, 
                  autonum = officer::run_autonum(seq_id = "tab", 
                                                 pre_label = "Table ", 
                                                 post_label = "\n", 
                                                 bkm = "anytable")) #%>%
  # font type
  #font(fontname="Times New Roman", part="all")
}



ecopolval4.fa[["Vaccounted"]] %>%
  as.data.frame() %>%
  rownames_to_column("Property") %>%
  #rename(Pdevelop = MR1, Ndevelop = MR2) %>%
    mutate(across(where(is.numeric), round, 3)) %>%
    flex("Eigenvalues and Variance Explained for Rotated Factor Solution")



```

```{r, echo = FALSE}
 # Adjust as per the number of factors

#fa.diagram(ecopolval4.fa, marg=c(.5,5,1,.5),size =1, adj = 0.25, e.size=.05,rsize=.35, main = "Four Factor Solution")

```



\newpage
## Option 1: Factor analysis on Scale 2 - Characteristics of the Technology
 2 factor solution 


```{r, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

#alpha test on Eco-pol characteristics of the technology

Nuclear <- codedmodule2 %>%
dplyr::select("DISPLACENUCLEAR":"RELYNUCLEAR") %>%
  na.omit()%>%
    rename(
   "Displacement risk(nuclear)" = "DISPLACENUCLEAR",
  "Pollution risk(nuclear)" = "POLLUTENUCLEAR",
  "Health risk(nuclear)" = "HEALTHNUCLEAR",
  "Job opportunities(nuclear)" = "JOBSNUCLEAR",
  "Spoils Natural Beauty(nuclear)" = "BEAUTYNUCLEAR",
  "Community pride(nuclear)" = "PRIDENUCLEAR",
  "National pride(nuclear)" = "NPRIDENUCLEAR",
  "National development(nuclear)" = "DEVNUCLEAR",
  "Local prosperity(nuclear)" = "PROSPERNUCLEAR",
  "Reliance on government(nuclear)" = "RELYNUCLEAR"
    )


Nuclear.fa <- fa(Nuclear, nfactors = 2, rotate = "varimax")

#print.psych(Nuclear.fa, cut = 0.40, sort = TRUE)

#fa.diagram(Nuclear.fa)


```


```{r, echo=FALSE}

library(flextable)

set_flextable_defaults(docx.landscape = TRUE)

flex <- function(data, title=NULL) {
  # this grabs the data and converts it to a flextbale
  flextable(data) %>%
  # this makes the table fill the page width
  set_table_properties(layout = "autofit", width = 1) %>%
  # font size
  fontsize(size=10, part="all") %>%
    #this adds a ttitlecreates an automatic table number
      set_caption(title, 
                  autonum = officer::run_autonum(seq_id = "tab", 
                                                 pre_label = "Table ", 
                                                 post_label = "\n", 
                                                 bkm = "anytable")) #%>%
  # font type
  #font(fontname="Times New Roman", part="all")
}

rename_map <- c(
  "Displacement risk(nuclear)" = "Nuclear energy is leading to displacement of people from their land",
  "Spoils Natural Beauty(nuclear)" = "Nuclear energy spoils the natural beauty of the landscape",
  "Pollution risk(nuclear)" = "Nuclear energy increases pollution of air/water/land",
  "Health risk(nuclear)" = "Nuclear energy poses a great risk to the health of people living around it",
  "Job opportunities(nuclear)" = "Nuclear energy will bring jobs to the local community",
  "Community pride(nuclear)" = "I would be proud if my community used nuclear energy",
  "National pride(nuclear)" = "Nuclear energy is a mark of pride for our nation",
  "National development(nuclear)" = "Nuclear energy pushes forward the country's development",
  "Local prosperity(nuclear)" = "Nuclear energy brings economic prosperity to the surrounding regions",
  "Reliance on government(nuclear)" = "I don't like the idea that I have to rely on the government for electricity from nuclear energy"
)


fa_table <- function(x, cut) {
  #get sorted loadings
  loadings <- fa.sort(x)$loadings %>% round(3)
  #suppress loadings
  loadings[loadings > -cut & loadings < cut] <- ""
  #get additional info  
  add_info <- cbind(x$communalities, 
                    x$uniquenesses,
                    x$complexity) %>%
    # make it a data frame
    as.data.frame() %>%
    # column names
    rename("Communality" = V1,
           "Uniqueness" = V2,
           "Complexity" = V3) %>%
    #get the item names from the vector
    rownames_to_column("item")
  
  #build table
  loadings %>%
    unclass() %>%
    as.data.frame() %>%
    rownames_to_column("item") %>%
    left_join(add_info) %>%
    mutate(
      item = if_else(item %in% names(rename_map), rename_map[item], item),
      code = names(rename_map)[match(item, rename_map)], # extracting short form
      across(where(is.numeric), round, 3)
    ) %>%
    select(code, everything()) # reorder columns to bring code to the front
}

fa_table(Nuclear.fa, .4) %>%
  rename("Negative Characteristics" = MR1, "Positive Characteristics" = MR2, Items= item, Code = code) %>%
  flex("Nuclear Energy: 2 factor solution") %>%
  autofit()


```

```{r, echo=FALSE}

library(flextable)


flex <- function(data, title=NULL) {
  # this grabs the data and converts it to a flextbale
  flextable(data) %>%
  # this makes the table fill the page width
  set_table_properties(layout = "autofit", width = 1) %>%
  # font size
  fontsize(size=10, part="all") %>%
    #this adds a ttitlecreates an automatic table number
      set_caption(title, 
                  autonum = officer::run_autonum(seq_id = "tab", 
                                                 pre_label = "Table ", 
                                                 post_label = "\n", 
                                                 bkm = "anytable")) #%>%
  # font type
  #font(fontname="Times New Roman", part="all")
}



Nuclear.fa[["Vaccounted"]] %>%
  as.data.frame() %>%
  rownames_to_column("Property") %>%
  rename("Negative Characteristics" = MR1, "Positive Characteristics" = MR2) %>%
    mutate(across(where(is.numeric), round, 3)) %>%
    flex("Eigenvalues and Variance Explained for 2 Factor Solution")



```


```{r, echo = FALSE}
 # Adjust as per the number of factors


#fa.diagram(Nuclear.fa, marg=c(.5,5,1,.5),size =1, adj = 0.25, e.size=.05,rsize=.35, main = "Two Factor Solution")

```



\newpage
