---
title: "moduleoneanalysis"
output:
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
    keep_md: true
    theme: paper
    df_print: paged
---

```{r load packages, warning = FALSE, message = FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(hablar))
suppressPackageStartupMessages(library(tsibble))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(ggplot2))

```



```{r, eval=TRUE}

moduleone <- read_excel( "~/Desktop/thesis_surveydata/livelihood_insecurity_complete.xlsx")
save(moduleone, file = "moduleone.rda")
module1 <- data.frame(moduleone)
module1 %>%
  filter(!row_number() %in% c(1,2))

# loaded data set for module 2 eco -pol variables and removes the rows with question number and question text
```



```{r, eval =TRUE}
#This chunk contains the coding schemes of various scales used in survey one: eco-political factors, kahan scale and acceptance scale
codedmodule1 <- module1 %>%
  
#remove row 1
  filter(!row_number() %in% c(1,2)) %>% 
  
# replace risky likert scale with numbers
  mutate_at(vars(starts_with("Risky")), funs(case_when(. =="Not at all risky" ~ 1, 
                                                       . =="Slightly risky" ~ 2, 
                                                       . =="Moderately risky" ~ 3, 
                                                       . =="Very risky" ~ 4, 
                                                       . =="Extremely risky" ~ 5))) %>%

# replace beneficial likert scale with numbers  
  mutate_at(vars(starts_with("Ben")), funs(case_when(. =="Not at all beneficial" ~ 1,
                                                     . =="Slightly beneficial" ~ 2,
                                                     . =="Moderately beneficial" ~ 3,
                                                     . =="Very beneficial" ~ 4,
                                                     . =="Extremely beneficial" ~ 5 ))) %>%

# replace nuclear acceptance likert scale with numbers
  mutate_at(vars(N_accept,N_reluctantlyaccept,N_reject), funs(case_when(. == "Strongly disagree" ~ 1, 
                                                                        . == "Somewhat disagree" ~ 2,
                                                                        . == "Neither agree nor disagree" ~3,
                                                                        . == "Somewhat agree" ~ 4,
                                                                        . == "Strongly agree" ~ 5)))

codedmodule1
  
#coded dependent variables for module 1 livelihood and income security survey


```

```{r}
# normalize quantitative livelihood-income security variables 




```

```{r}
#trying to work with likert packages here 

likertstack <- module2%>%
  filter(!row_number() %in% c(1,2)) %>% 
  select(starts_with("RISKY"))%>%
  gather(Technology, Perceived_Risk, Risky_Hydro:Risky_INDLPG, factor_key = TRUE)%>%
  separate(Technology, c("Risky", "Technology"), extra = "merge", fill = "left")%>%
  select(-Risky) %>% 
  group_by(Technology, Perceived_Risk) %>%
  summarise(n=n()) %>%
  pivot_wider(names_from = "Perceived_Risk", values_from = "n")


likert(Measure ~ ., data=likertstack, ylab=NULL,
       ReferenceZero=3, as.percent=TRUE,
       positive.order=TRUE, 
       main = list("Pereived risk from energy technologies in India",x=unit(.55, "npc")), 
       sub= list("Perceived risk",x=unit(.57, "npc")), 
       xlim=c(-40,-20,0,20,40,60,80,100),
       strip=FALSE, 
       par.strip.text=list(cex=.7))
```

