---
title: "demographicvariablesregression"

output:
  html_document:
    fig_width: 9
    fig_height: 6
    fig_caption: yes
    keep_md: yes
    theme: paper
    df_print: paged
  pdf_document: 
    
    toc: yes
    number_sections: yes
    toc_depth: 2
    fig_width: 9
    fig_height: 6
    fig_caption: yes
---

```{r load packages, warning = FALSE, message = FALSE, echo=FALSE}
  knitr::opts_chunk$set(warning = FALSE, message = FALSE)

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))

```


```{r, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
moduletwo <- read_excel(here::here("thesis_surveydata/political_factors_complete.xlsx"))
module2 <- data.frame(moduletwo)
module2[module2 == "Rather not say/ Don't know"] <- "Rather not say/Don't know"

# loaded data set for module 2 eco -pol variables and removes the rows with question number and question text
```


```{r, eval =TRUE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
#This chunk contains the coding schemes of various scales used in survey one: eco-political factors, kahan scale and acceptance scale
codedmodule2 <- module2 %>%
  
#remove row 1
  filter(!row_number() %in% c(1,2)) %>% 
  
# replace risky likert scale with numbers
  mutate_at(vars(starts_with("Risky")), funs(case_when(. =="Not at all risky" ~ 1, 
                                                       . =="Slightly risky" ~ 2, 
                                                       . =="Moderately risky" ~ 3, 
                                                       . =="Very risky" ~ 4, 
                                                       . =="Extremely risky" ~ 5))) %>%

# replace beneficial likert scale with numbers  
  mutate_at(vars(starts_with("Ben")), funs(case_when(. =="Not at all beneficial" ~ 1,
                                                     . =="Slightly beneficial" ~ 2,
                                                     . =="Moderately beneficial" ~ 3,
                                                     . =="Very beneficial" ~ 4,
                                                     . =="Extremely beneficial" ~ 5 ))) %>%

# replace nuclear acceptance likert scale with numbers
  mutate_at(vars(N_accept,N_reluctantlyaccept,N_reject), funs(case_when(. == "Strongly disagree" ~ 1, 
                                                                        . == "Somewhat disagree" ~ 2,
                                                                        . == "Neither agree nor disagree" ~3,
                                                                        . == "Somewhat agree" ~ 4,
                                                                        . == "Strongly agree" ~ 5))) %>%
  
# code likert scale for variables for Kahan scale into numbers
  mutate_at(vars(starts_with (c("K_I","K_H","DISPLACE", "POLLUTE", "HEALTH", "JOBS", "BEAUTY", "PRIDE", "NPRIDE", "DEV", "PROSPER", "RELY"))), funs(case_when(. == "Strongly disagree" ~ 1, 
               . == "Somewhat disagree" ~ 2,
               . == "Neither agree nor disagree" ~3,
               . == "Somewhat agree" ~ 4,
               . == "Strongly agree" ~ 5))) %>%
  
# reverse code for likert scale for variables for Kahan scale into numbers
  mutate_at(vars(starts_with (c("K_S","K_E"))), funs(case_when(. == "Strongly disagree" ~ 5, 
                                                               . == "Somewhat disagree" ~ 4,
                                                               . == "Neither agree nor disagree" ~3,
                                                               . == "Somewhat agree" ~ 2,
                                                               . == "Strongly agree" ~ 1))) %>%

# code eco-pol scale variables into numbers
  mutate_at(vars(SYSTEMDEMO,SYSTEMRELIGION,SYSTEMTECHNO,SYSTEMTOTAL,WEALTHLIM,MECHANISATION,DECISIONDECEN,INDUSTRYLARGE,ECONOMYGLOBAL,OWNERPVT,OWNERNOREG), funs(case_when(. == "Strongly disagree" ~ 1, 
                        . == "Somewhat disagree" ~ 2,
                        . == "Neither agree nor disagree" ~3,
                        . == "Somewhat agree" ~ 4,
                        . == "Strongly agree" ~ 5))) %>%

# reverse code eco-pol scale variables into numbers 
 mutate_at(vars(DECISIONCEN, INDUSTRYSMALL, ECONOMYLOCAL, ENVOVERDEV,OWNERPUB, OWNERREG), funs(case_when(. == "Strongly disagree" ~ 5, 
                                                                                                         . == "Somewhat disagree" ~ 4,
                                                                                                         . == "Neither agree nor disagree" ~3,
                                                                                                         . == "Somewhat agree" ~ 2,
                                                                                                         . == "Strongly agree" ~ 1)))

```


```{r, eval=TRUE, echo=FALSE}

moduleone <- read_excel(here::here("thesis_surveydata/livelihood_insecurity_complete.xlsx"))
module1 <- data.frame(moduleone)

# loaded data set for module 2 eco -pol variables and removes the rows with question number and question text
```



```{r, eval =TRUE, echo=FALSE}
#This chunk contains the coding schemes of likert scales 
codedmodule1 <- module1 %>%
  
#remove row 1
  filter(!row_number() %in% c(1,2)) %>% 
  
# replace risky likert scale with numbers
  mutate_at(vars(starts_with("Risky")), funs(case_when(. =="Not at all risky" ~ 1, 
                                                       . =="Slightly risky" ~ 2, 
                                                       . =="Moderately risky" ~ 3, 
                                                       . =="Very risky" ~ 4, 
                                                       . =="Extremely risky" ~ 5))) %>%

# replace beneficial likert scale with numbers  
  mutate_at(vars(starts_with("Ben")), funs(case_when(. =="Not at all beneficial" ~ 1,
                                                     . =="Slightly beneficial" ~ 2,
                                                     . =="Moderately beneficial" ~ 3,
                                                     . =="Very beneficial" ~ 4,
                                                     . =="Extremely beneficial" ~ 5 ))) %>%

# replace nuclear acceptance likert scale with numbers
  mutate_at(vars(N_accept,N_reluctantlyaccept,N_reject), funs(case_when(. == "Strongly disagree" ~ 1, 
                                                                        . == "Somewhat disagree" ~ 2,
                                                                        . == "Neither agree nor disagree" ~3,
                                                                        . == "Somewhat agree" ~ 4,
                                                                        . == "Strongly agree" ~ 5)))

```

```{r, echo = FALSE}

suppressPackageStartupMessages(library(tidyselect))
# combine codedmodule1 and codedmodule2

numcol2 <- codedmodule2 %>% add_column(Respondent = 1:1099, .before = "Language") 
numcol1 <- codedmodule1 %>% add_column(Respondent = 1099:2160, .before = "Language")

joineddf <-  full_join(numcol2, numcol1, by = c("Respondent", "Language", "Survey_Date", "State", "Risky_Hydro", "Risky_Solar", "Risky_Wind", "Risky_Nuclear", "Risky_Coal", "Risky_Gas", "Risky_Oil", "Risky_INDHydro", "Risky_INDSolar", "Risky_INDWind", "Risky_INDBiogas", "Risky_INDDiesel", "Risky_INDKerosene", "Risky_INDFirewoodetc", "Risky_INDLPG", "Ben_Hydro", "Ben_Solar", "Ben_Wind", "Ben_Nuclear", "Ben_Coal", "Ben_Gas", "Ben_Oil", "Ben_INDHydro", "Ben_INDSolar", "Ben_INDWind", "Ben_INDDiesel", "Ben_INDBiogas", "Ben_INDFirewoodetc", "Ben_INDLPG", "Ben_INDKerosene", "N_accept", "N_reluctantlyaccept", "N_reject", "age", "urban_rural", "gender", "caste", "religion", "religiontext")) 




```



```{r, echo=FALSE}

# cleaning up variables and making them into neat categories, turning IVs into factors 

library(dplyr)

demovars <- joineddf %>%
  dplyr::select(starts_with("Risky"), starts_with("Ben"),urban_rural, gender, caste, religion, age, State)%>%
  mutate(religion = ifelse(religion == "Other (Please mention)", "Other", religion)) %>%
  filter(gender %in% c("Male", "Female"))%>%
  mutate(caste = ifelse(grepl("SC|Scheduled caste", caste), "SC", caste),
          caste = ifelse(grepl("ST|Scheduled Tribe", caste), "ST", caste),
          caste = ifelse(grepl("OBC|Other Backward Classes", caste), "OBC", caste))%>%
  mutate(State = case_when(State == "West bengal" ~ "West Bengal",
                            State == "WEST BENGAL" ~ "West Bengal",
                            State == "Up" ~ "UP",
                            TRUE ~ State)) %>%
  mutate(religion = case_when(religion == "Agnostism/ Atheism" ~ "Agnosticism_Atheism",
                              TRUE~ religion))


demovars$gender <- as.factor(demovars$gender)
demovars$caste <- as.factor(demovars$caste)
demovars$urban_rural <- as.factor(demovars$urban_rural)
demovars$age <- as.factor(demovars$age)
demovars$religion <- as.factor(demovars$religion)
demovars$State <- as.factor(demovars$State)



```


```{r, echo=FALSE}
library(dplyr)

demovars_frisk <- demovars %>%
  select(starts_with("Risky"), gender) %>%
  filter(gender == "Female")%>%
  na.omit()


demovars_mrisk <- demovars %>%
  select(starts_with("Risky"), gender) %>%
  filter(gender == "Male") %>%
  na.omit()

  
sum_frisk <- demovars_frisk %>% 
    summarise(across(starts_with("Risky"), list(mean = mean, sd = sd, median = median, n = nrow))) %>%
    pivot_longer(cols = starts_with("Risky"), 
                                          names_to = c("Risky", "Technology", "stat"), 
                                          names_sep =  "_",
                                          values_to = "Value")%>%
    select(-Risky) %>%
    pivot_wider(names_from = stat, values_from = Value)%>%
    mutate(gender = "f")


sum_mrisk <- demovars_mrisk %>% 
    summarise(across(starts_with("Risky"), list(mean = mean, sd = sd, median = median, n = nrow))) %>%
    pivot_longer(cols = starts_with("Risky"), 
                                          names_to = c("Risky", "Technology", "stat"), 
                                          names_sep =  "_",
                                          values_to = "Value")%>%
                                         
    select(-Risky) %>%
    pivot_wider(names_from = stat, values_from = Value)%>%
    mutate(gender = "m")



```





```{r, echo=FALSE}
library(ggplot2)

# Combine the two datasets
sum_gender <- rbind(sum_frisk, sum_mrisk)

# Plot

p1 <- sum_gender%>% 
  filter(Technology %in% c("Wind","Nuclear","Solar","Oil","Hydro","Gas","Coal")) %>%
  ggplot(aes(x=Technology, y= median, fill = gender))+
  geom_bar(stat="identity", position=position_dodge())+
  #geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=0.2, position=position_dodge(0.9)) +
  ylim(0,5)+
  scale_fill_manual(values=c("red", "blue"), name="legend")+
  labs(y = "Median perceivd risk", x = "Energy Technologies")+
  ggtitle("Perceived risk and benefit from centrally owned energy technologies by gender")+
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5))+
  annotate("text", x=c("Solar", "Nuclear", "Coal"), y=4.8, label="*", size=10, fontface="bold") +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5, size=12, margin=margin(l=50)))


p2 <- sum_gender%>% 
  filter(Technology %in% c("INDHydro", "INDSolar", "INDWind", "INDBiogas","INDDiesel", "INDKerosene","INDFirewoodetc","INDLPG")) %>%
  ggplot(aes(x=Technology, y= median, fill = gender))+
  geom_bar(stat="identity", position=position_dodge())+
  #geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=0.2, position=position_dodge(0.9)) +
  ylim(0,5)+
  scale_fill_manual(values=c("red", "blue"), name="legend")+
  labs(y = "Median perceived risk", x = "Energy Technologies")+
  ggtitle("Perceived risk and benefit from individually owned energy technologies by gender")+
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5)) +
  annotate("text", x=c("INDSolar", "INDBiogas", "INDDiesel"), y=4.8, label="*", size=10, fontface="bold") +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5, size=12, margin=margin(l=50)))


library(gridExtra)
grid.arrange(p1, p2, ncol = 2, widths = NULL)

```

```{r, echo=FALSE}

# conducting non-parametric procedure : "Wilcoxon rank-sum test" to see how perception of risk may differ according to gender. 

library(broom)
library(stats)
library(dplyr)

male_risk<- demovars[demovars$gender == "Male",]$Risky_Nuclear 
female_risk <- demovars[demovars$gender == "Female",]$Risky_Nuclear 

wilcox.test(male_risk, female_risk, alternative = "two.sided")


Cmale_risk<- demovars[demovars$gender == "Male",]$Risky_Coal 
Cfemale_risk <- demovars[demovars$gender == "Female",]$Risky_Coal 

wilcox.test(Cmale_risk, Cfemale_risk, alternative = "two.sided")

wilcox_gender <- demovars %>%
  dplyr::select(starts_with("Risky")) %>%
  lapply(function(col) wilcox.test(col ~ gender, data = demovars))

wilcox_mf <- do.call(rbind, wilcox_gender)

# results from this are used to mark significant differences in the bar graph above. 



```



```{r, echo=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)

demovars_caste <- demovars %>%
  dplyr::select(starts_with("Risky"), caste) %>%
  na.omit()


demovars_caste_long <- demovars_caste %>%
  pivot_longer(cols = starts_with("Risky_"), names_to = "technology", values_to = "perceived_risk") %>%
  mutate(technology = gsub("Risky_", "", technology)) 



```



```{r, echo=FALSE}

library(ggplot2)


# Subset dataframe with IND prefix
demovars_caste_long_ind <- demovars_caste_long %>% 
  filter(str_starts(technology, "IND"))%>%
   group_by(caste, technology) %>% 
  summarize(median_perceived_risk = median(perceived_risk))

table(demovars_caste_long_ind)

# Create bar graph with IND prefix 
ggplot(demovars_caste_long_ind, aes(x = technology, y = median_perceived_risk, fill = caste)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Median Perceived Risk by Caste Groups for Technologies with IND Prefix",
       x = "Technology", y = "Median Perceived Risk") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) # Rotate x-axis labels

# Subset dataframe without IND prefix
demovars_caste_long_not_ind <- demovars_caste_long %>% 
  filter(!str_starts(technology, "IND"))%>%
   group_by(caste, technology) %>% 
  summarize(median_perceived_risk = median(perceived_risk))

# Create bar graph without IND prefix 

ggplot(demovars_caste_long_not_ind, aes(x = technology, y = median_perceived_risk, fill = caste)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Median Perceived Risk by Caste Groups for Technologies without IND Prefix",
       x = "Technology", y = "Median Perceived Risk") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) # Rotate x-axis labels


```


```{r}

# print the head of the file
head(demovars_caste_long)


# Show the group/caste levels

demovars_caste_long$caste <- factor(demovars_caste_long$caste)
levels(demovars_caste_long$caste)

# compute summary statistic by groups 
library(dplyr)
summary_caste <- group_by(demovars_caste_long, caste) %>%
  summarise(
    count = n(),
    mean = mean(perceived_risk, na.rm = TRUE),
    sd = sd(perceived_risk, na.rm = TRUE),
    median = median(perceived_risk, na.rm = TRUE),
    IQR = IQR(perceived_risk, na.rm = TRUE)
  )


summary(summary_caste)

library(ggplot2)

# Create the box plot with median values



```

```{r}

demovars_caste_long$technology <- factor(demovars_caste_long$technology)
levels(demovars_caste_long$technology)


kruskal.test(perceived_risk ~ caste, data = demovars_caste_long)

pairwise.wilcox.test(demovars_caste_long$perceived_risk, demovars_caste_long$caste,
                 p.adjust.method = "BH")

library(dplyr)
#for Nuclear
Nuclear_caste <- demovars_caste_long %>%
  filter(technology == "Nuclear")

pairwise.wilcox.test(Nuclear_caste$perceived_risk, Nuclear_caste$caste,
                 p.adjust.method = "BH")


# For Coal
Coal_caste <- demovars_caste_long %>%
  filter(technology == "Coal")
pairwise.wilcox.test(Coal_caste$perceived_risk, Coal_caste$caste, p.adjust.method = "BH")

# For Gas
Gas_caste <- demovars_caste_long %>%
  filter(technology == "Gas")
pairwise.wilcox.test(Gas_caste$perceived_risk, Gas_caste$caste, p.adjust.method = "BH")

# For Hydro
Hydro_caste <- demovars_caste_long %>%
  filter(technology == "Hydro")
pairwise.wilcox.test(Hydro_caste$perceived_risk, Hydro_caste$caste, p.adjust.method = "BH")

# For INDBiogas
INDBiogas_caste <- demovars_caste_long %>%
  filter(technology == "INDBiogas")
pairwise.wilcox.test(INDBiogas_caste$perceived_risk, INDBiogas_caste$caste, p.adjust.method = "BH")

# For INDDiesel
INDDiesel_caste <- demovars_caste_long %>%
  filter(technology == "INDDiesel")
pairwise.wilcox.test(INDDiesel_caste$perceived_risk, INDDiesel_caste$caste, p.adjust.method = "BH")

# For INDFirewoodetc
INDFirewoodetc_caste <- demovars_caste_long %>%
  filter(technology == "INDFirewoodetc")
pairwise.wilcox.test(INDFirewoodetc_caste$perceived_risk, INDFirewoodetc_caste$caste, p.adjust.method = "BH")

# For INDHydro
INDHydro_caste <- demovars_caste_long %>%
  filter(technology == "INDHydro")
pairwise.wilcox.test(INDHydro_caste$perceived_risk, INDHydro_caste$caste, p.adjust.method = "BH")

# For INDKerosene
INDKerosene_caste <- demovars_caste_long %>%
  filter(technology == "INDKerosene")
pairwise.wilcox.test(INDKerosene_caste$perceived_risk, INDKerosene_caste$caste, p.adjust.method = "BH")

# For INDLPG
INDLPG_caste <- demovars_caste_long %>%
  filter(technology == "INDLPG")
pairwise.wilcox.test(INDLPG_caste$perceived_risk, INDLPG_caste$caste, p.adjust.method = "BH")

# For INDSolar
INDSolar_caste <- demovars_caste_long %>%
  filter(technology == "INDSolar")
pairwise.wilcox.test(INDSolar_caste$perceived_risk, INDSolar_caste$caste, p.adjust.method = "BH")

# For INDWind
INDWind_caste <- demovars_caste_long %>%
  filter(technology == "INDWind")
pairwise.wilcox.test(INDWind_caste$perceived_risk, INDWind_caste$caste, p.adjust.method = "BH")

# For Oil
Oil_caste <- demovars_caste_long %>%
  filter(technology == "Oil")
pairwise.wilcox.test(Oil_caste$perceived_risk, Oil_caste$caste, p.adjust.method = "BH")


# For Solar
Solar_caste <- demovars_caste_long %>%
  filter(technology == "Solar")
pairwise.wilcox.test(Solar_caste$perceived_risk, Solar_caste$caste, p.adjust.method = "BH")



# For Wind
Wind_caste <- demovars_caste_long %>%
  filter(technology == "Wind")
pairwise.wilcox.test(Wind_caste$perceived_risk, Wind_caste$caste, p.adjust.method = "BH")



#not finding any significant differences in the medians 

```
```{r}

demovars_urban_rural <-  demovars %>%
  select(starts_with("Risky"), urban_rural) %>%
  pivot_longer(cols = starts_with("Risky_"), names_to = "technology", values_to = "perceived_risk") %>%
  mutate(technology = gsub("Risky_", "", technology)) %>%
  na.omit()


pairwise.wilcox.test(demovars_urban_rural$perceived_risk, demovars_urban_rural$urban_rural, p.adjust.method = "BH")


# For Coal
Coal_urban_rural <- demovars_urban_rural %>%
  filter(technology == "Coal")
pairwise.wilcox.test(Coal_urban_rural$perceived_risk, Coal_urban_rural$urban_rural, p.adjust.method = "BH")

# For Gas
Gas_urban_rural <- demovars_urban_rural %>%
  filter(technology == "Gas")
pairwise.wilcox.test(Gas_urban_rural$perceived_risk, Gas_urban_rural$urban_rural, p.adjust.method = "BH")

# For Hydro
Hydro_urban_rural <- demovars_urban_rural %>%
  filter(technology == "Hydro")
pairwise.wilcox.test(Hydro_urban_rural$perceived_risk, Hydro_urban_rural$urban_rural, p.adjust.method = "BH")

# For INDBiogas
INDBiogas_urban_rural <- demovars_urban_rural %>%
  filter(technology == "INDBiogas")
pairwise.wilcox.test(INDBiogas_urban_rural$perceived_risk, INDBiogas_urban_rural$urban_rural, p.adjust.method = "BH")

# For INDDiesel
INDDiesel_urban_rural <- demovars_urban_rural %>%
  filter(technology == "INDDiesel")
pairwise.wilcox.test(INDDiesel_urban_rural$perceived_risk, INDDiesel_urban_rural$urban_rural, p.adjust.method = "BH")

# For INDFirewoodetc
INDFirewoodetc_urban_rural <- demovars_urban_rural %>%
  filter(technology == "INDFirewoodetc")
pairwise.wilcox.test(INDFirewoodetc_urban_rural$perceived_risk, INDFirewoodetc_urban_rural$urban_rural, p.adjust.method = "BH")

# For INDHydro
INDHydro_urban_rural <- demovars_urban_rural %>%
  filter(technology == "INDHydro")
pairwise.wilcox.test(INDHydro_urban_rural$perceived_risk, INDHydro_urban_rural$urban_rural, p.adjust.method = "BH")

# For INDKerosene
INDKerosene_urban_rural <- demovars_urban_rural %>%
  filter(technology == "INDKerosene")
pairwise.wilcox.test(INDKerosene_urban_rural$perceived_risk, INDKerosene_urban_rural$urban_rural, p.adjust.method = "BH")

# For INDLPG
INDLPG_urban_rural <- demovars_urban_rural %>%
  filter(technology == "INDLPG")
pairwise.wilcox.test(INDLPG_urban_rural$perceived_risk, INDLPG_urban_rural$urban_rural, p.adjust.method = "BH")

# For INDSolar
INDSolar_urban_rural <- demovars_urban_rural %>%
  filter(technology == "INDSolar")
pairwise.wilcox.test(INDSolar_urban_rural$perceived_risk, INDSolar_urban_rural$urban_rural, p.adjust.method = "BH")

# For INDWind
INDWind_urban_rural <- demovars_urban_rural %>%
 filter(technology == "INDWind")
pairwise.wilcox.test(INDWind_urban_rural$perceived_risk, INDWind_urban_rural$urban_rural, p.adjust.method = "BH")

#For Nuclear
Nuclear_urban_rural <- demovars_urban_rural %>%
filter(technology == "Nuclear")
pairwise.wilcox.test(Nuclear_urban_rural$perceived_risk, Nuclear_urban_rural$urban_rural, p.adjust.method = "BH")

#For Oil
Oil_urban_rural <- demovars_urban_rural %>%
filter(technology == "Oil")
pairwise.wilcox.test(Oil_urban_rural$perceived_risk, Oil_urban_rural$urban_rural, p.adjust.method = "BH")

#For Solar
Solar_urban_rural <- demovars_urban_rural %>%
filter(technology == "Solar")
pairwise.wilcox.test(Solar_urban_rural$perceived_risk, Solar_urban_rural$urban_rural, p.adjust.method = "BH")

#For Wind
Wind_urban_rural <- demovars_urban_rural %>%
filter(technology == "Wind")
pairwise.wilcox.test(Wind_urban_rural$perceived_risk, Wind_urban_rural$urban_rural, p.adjust.method = "BH")



```


```{r}
library(ggplot2)

# Convert variables to factors
demovars_urban_rural$urban_rural <- factor(demovars_urban_rural$urban_rural)
demovars_urban_rural$technology <- factor(demovars_urban_rural$technology)

# Create boxplot
ggplot(demovars_urban_rural, aes(x = technology, y = perceived_risk, fill = urban_rural)) +
  stat_boxplot(geom="errorbar", width=0.5) +
  stat_boxplot(geom="boxplot", width=0.5, notch=FALSE, outlier.shape=NA) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
  labs(x = "Technology", y = "Perceived Risk", fill = "Urban/Rural") +
  theme_bw() +
   theme(legend.position = "bottom", plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  ggtitle("Perceived Risk by Technology and Urban/Rural Group") +
  facet_wrap(~ifelse(grepl("^IND", technology), "IND", "Non-IND"), nrow = 1)

```


```{r}
# now check for urban and gender since caste is not that important , I don't care about age. let's do a regression 

str(demovars)

```

```{r}
library(dplyr)
demovars_subset <- demovars %>%
  na.omit()%>%
  select(-c(urban_rural, gender, caste, religion, age, State))

# correlation matric to check correlations among the DVs
correlation_matrix <- round(cor(demovars_subset), 2)

# Convert correlation matrix to data frame
cor_df <- as.data.frame(as.table(correlation_matrix))

# Rename columns
colnames(cor_df) <- c("Var1", "Var2", "Correlation")

# Extract variables with correlation greater than 0.7
high_corr_vars <- subset(cor_df, abs(Correlation) > 0.7) %>%
                  filter(Var1 != Var2)



# We see that Risky_INDSolar and Risky_Solar are highly correlated concepts (as expected) but rest of the dependent variables are not highly correlated. In the context of dependent variables, high correlation between them can indicate that they are measuring similar constructs or dimensions, which can lead to redundancy in the model. In some cases, it may be necessary to combine these variables or choose one to represent the construct in the analysis. Additionally, high correlation between dependent variables can make it difficult to isolate the effect of individual independent variables on each dependent variable. Therefore, it is important to check the correlation between different dependent variables to ensure that the model is accurately capturing the relationships between the independent and dependent variables. 

# Here we don't need to worry about this because we are going to run two separate regression models. one for IND and one for centrally owned technologies. SO NO HIGH MULTICOLINEARITY - GOOD NEWS! 


```

```{r}
# I want to conduct a factor analysis on my IVs to see how closely connected some of the caste and religion categories might be. 
library(psych)








```


```{r}
# what is the appropriate regression model to use? First I consider the regression model used in risk studies? 
# First question is does WME (upper caste male effect exist in India, or what demographic factors impact risk perception of energy technologies.)
# going to use linear regression - following Kahan et al. 

# running multivariate regression model on risk perception fom centrally owned energy technologies: 

model_Risky_central <- demovars %>%
  dplyr::select(dplyr::starts_with("Risky"), age, urban_rural, gender, caste, religion, State) %>%
  dplyr::select(-dplyr::starts_with("Risky_IND")) %>%
  na.omit()%>%
#creating dummy variables
  mutate(gender_female = if_else(gender == "Female", 1, 0),
         caste_brahmin = if_else(caste == "Brahmin", 1, 0),
         caste_general = if_else(caste == "General", 1, 0),
         caste_obc = if_else(caste == "OBC", 1, 0),
         caste_rather_not_say = if_else(caste == "Rather not say/Don't know", 1, 0),
         caste_sc = if_else(caste == "SC", 1, 0),
         caste_st = if_else(caste == "ST", 1, 0),
         urban_rural_rural = if_else(urban_rural == "Rural", 1, 0),
         age_18_24 = if_else(age == "18-24 years old", 1, 0),
         age_25_34 = if_else(age == "25-34 years old", 1, 0),
         age_35_44 = if_else(age == "35-44 years old", 1, 0),
         age_45_54 = if_else(age == "45-54 years old", 1, 0),
         age_55_64 = if_else(age == "55-64 years old", 1, 0),
         age_65_74 = if_else(age == "65-74 years old", 1, 0),
         age_75_or_older = if_else(age == "75 years or older", 1, 0),
         religion_agnosticism_atheism = if_else(religion == "Agnosticism_Atheism", 1, 0),
         religion_buddhism = if_else(religion == "Buddhism", 1, 0),
         religion_christanity = if_else(religion == "Christanity", 1, 0),
         religion_hinduism = if_else(religion == "Hinduism", 1, 0),
         religion_islam = if_else(religion == "Islam", 1, 0),
         religion_jainism = if_else(religion == "Jainism", 1, 0),
         religion_other = if_else(religion == "Other", 1, 0),
         religion_sikhism = if_else(religion == "Sikhism", 1, 0),
         state_maharashtra = if_else(State == "Maharashtra", 1, 0),
         state_rajasthan = if_else(State == "Rajasthan", 1, 0),
         state_tamilnadu = if_else(State == "Tamilnadu", 1, 0),
         state_up = if_else(State == "UP", 1, 0),
         state_west_bengal = if_else(State == "West Bengal", 1, 0))



# Fit a multivariate linear regression model
model <- lm(cbind(Risky_Hydro, Risky_Solar, Risky_Wind, Risky_Nuclear, Risky_Coal, Risky_Gas, Risky_Oil) ~ gender_female + caste_general + caste_obc + caste_rather_not_say + caste_sc + caste_st + urban_rural_rural + age_25_34 + age_35_44 + age_45_54 + age_55_64 + age_65_74 + age_75_or_older + religion_buddhism + religion_christanity + religion_hinduism + religion_islam + religion_jainism + religion_other + religion_sikhism + state_rajasthan + state_tamilnadu + state_up + state_west_bengal, data = model_Risky_central)


# Print the model summary
summary(model)

str(model_Risky_central)


#NEXT - plot residuals, read about regression on statistics by Jim. move on to factor analysis and reducing factors and conducting regression models and residual plots, send these to Terre, Milind and Ramana - questions and ideas for two papers. - right now the results from the regression do not match the earlier results like the significance of gender for instance 


  
```


