---
title: "module2IVgraphs"
output: 
html_document:
    fig_width: 9
    fig_height: 6
    fig_caption: yes
    keep_md: yes
    theme: paper
    df_print: paged
  
  
pdf_document: 
    
    toc: true
    number_sections: true
    toc_depth: 2
    fig_width: 9
    fig_height: 6
    fig_caption: yes
---

```{r load packages, warning = FALSE, message = FALSE, echo=FALSE}
  knitr::opts_chunk$set(warning = FALSE, message = FALSE)

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(tsibble))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(ggplot2))

```


```{r, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
moduletwo <- read_excel(here::here("thesis_surveydata/political_factors_complete.xlsx"))
save(moduletwo, file = "moduletwo.rda")
module2 <- data.frame(moduletwo)
module2[module2 == "Rather not say/ Don't know"] <- "Rather not say/Don't know"
module2 %>%
  filter(!row_number() %in% c(1,2))

# loaded data set for module 2 eco -pol variables and removes the rows with question number and question text
```

```{r, echo = FALSE}

#This chunk contains the coding schemes of various scales used in survey one: eco-political factors, kahan scale and acceptance scale
codedmodule2 <- module2 %>%
  
#remove row 1
  filter(!row_number() %in% c(1,2)) %>% 
  
# replace risky likert scale with numbers
  mutate_at(vars(starts_with("Risky")), funs(case_when(. =="Not at all risky" ~ 1, 
                                                       . =="Slightly risky" ~ 2, 
                                                       . =="Moderately risky" ~ 3, 
                                                       . =="Very risky" ~ 4, 
                                                       . =="Extremely risky" ~ 5))) %>%

# replace beneficial likert scale with numbers  
  mutate_at(vars(starts_with("Ben")), funs(case_when(. =="Not at all beneficial" ~ 1,
                                                     . =="Slightly beneficial" ~ 2,
                                                     . =="Moderately beneficial" ~ 3,
                                                     . =="Very beneficial" ~ 4,
                                                     . =="Extremely beneficial" ~ 5 ))) %>%

# replace nuclear acceptance likert scale with numbers
  mutate_at(vars(N_accept,N_reluctantlyaccept,N_reject), funs(case_when(. == "Strongly disagree" ~ 1, 
                                                                        . == "Somewhat disagree" ~ 2,
                                                                        . == "Neither agree nor disagree" ~3,
                                                                        . == "Somewhat agree" ~ 4,
                                                                        . == "Strongly agree" ~ 5))) %>%
  
# code likert scale for variables for Kahan scale into numbers
  mutate_at(vars(starts_with (c("K_I","K_H","DISPLACE", "POLLUTE", "HEALTH", "JOBS", "BEAUTY", "PRIDE", "NPRIDE", "DEV", "PROSPER", "RELY"))), funs(case_when(. == "Strongly disagree" ~ 1, 
               . == "Somewhat disagree" ~ 2,
               . == "Neither agree nor disagree" ~3,
               . == "Somewhat agree" ~ 4,
               . == "Strongly agree" ~ 5))) %>%
  
# reverse code for likert scale for variables for Kahan scale into numbers
  mutate_at(vars(starts_with (c("K_S","K_E"))), funs(case_when(. == "Strongly disagree" ~ 5, 
                                                               . == "Somewhat disagree" ~ 4,
                                                               . == "Neither agree nor disagree" ~3,
                                                               . == "Somewhat agree" ~ 2,
                                                               . == "Strongly agree" ~ 1))) %>%

# code eco-pol scale variables into numbers
  mutate_at(vars(SYSTEMDEMO,SYSTEMRELIGION,SYSTEMTECHNO,SYSTEMTOTAL,WEALTHLIM,MECHANISATION,DECISIONDECEN,INDUSTRYLARGE,ECONOMYGLOBAL,OWNERPVT,OWNERNOREG), funs(case_when(. == "Strongly disagree" ~ 1, 
                        . == "Somewhat disagree" ~ 2,
                        . == "Neither agree nor disagree" ~3,
                        . == "Somewhat agree" ~ 4,
                        . == "Strongly agree" ~ 5))) %>%

# reverse code eco-pol scale variables into numbers 
 mutate_at(vars(DECISIONCEN, INDUSTRYSMALL, ECONOMYLOCAL, ENVOVERDEV,OWNERPUB, OWNERREG), funs(case_when(. == "Strongly disagree" ~ 5, 
                                                                                                         . == "Somewhat disagree" ~ 4,
                                                                                                         . == "Neither agree nor disagree" ~3,
                                                                                                         . == "Somewhat agree" ~ 2,
                                                                                                         . == "Strongly agree" ~ 1)))

codedmodule2
  

```




```{r, echo = FALSE}
demorisk <- codedmodule2%>%
  group_by(SYSTEMDEMO)%>%
  filter(SYSTEMDEMO == 5)%>%
  summarize_at(vars(starts_with(c("RISKY"))), list(~mean(., na.rm = TRUE), ~median(., na.rm = TRUE), ~sd(.,na.rm = TRUE),~var(.,na.rm = TRUE), ~n())) %>%
  #melt to long format
  gather(key = "technology", value = "summary", Risky_Hydro_mean, Risky_Solar_mean, Risky_Wind_mean, Risky_Nuclear_mean, Risky_Coal_mean, Risky_Gas_mean, Risky_Oil_mean, Risky_Hydro_sd, Risky_Solar_sd, Risky_Wind_sd, Risky_Nuclear_sd, Risky_Coal_sd, Risky_Gas_sd, Risky_Oil_sd) %>%
  select(SYSTEMDEMO, technology, summary) %>%
  # separate risky from variable suffix
  separate(technology, c("Risky", "var"), extra = "merge", fill = "left") %>%
  #separate mean from variable prefix
  separate(var, c("technology", "meansd")) %>%
  # spread summary values back to wide form
  spread(meansd,summary) %>%
  #clean up
  select(-Risky)%>%
  arrange(mean) %>%
  mutate_at(vars(SYSTEMDEMO), funs(case_when(. == 5 ~ "democractic"))) %>%
  dplyr::rename(Govt = SYSTEMDEMO)

techrisk <- codedmodule2%>%
  group_by(SYSTEMTECHNO)%>%
  filter(SYSTEMTECHNO == 5)%>%
  summarize_at(vars(starts_with(c("RISKY"))), list(~mean(., na.rm = TRUE), ~median(., na.rm = TRUE), ~sd(.,na.rm = TRUE),~var(.,na.rm = TRUE), ~n())) %>%
  #melt to long format
  gather(key = "technology", value = "summary", Risky_Hydro_mean, Risky_Solar_mean, Risky_Wind_mean, Risky_Nuclear_mean, Risky_Coal_mean, Risky_Gas_mean, Risky_Oil_mean, Risky_Hydro_sd, Risky_Solar_sd, Risky_Wind_sd, Risky_Nuclear_sd, Risky_Coal_sd, Risky_Gas_sd, Risky_Oil_sd) %>%
  select(SYSTEMTECHNO, technology, summary) %>%
  # separate risky from variable suffix
  separate(technology, c("Risky", "var"), extra = "merge", fill = "left") %>%
  #separate mean from variable prefix
  separate(var, c("technology", "meansd")) %>%
  # spread summary values back to wide form
  spread(meansd,summary) %>%
  #clean up
  select(-Risky)%>%
  arrange(mean) %>%
  mutate_at(vars(SYSTEMTECHNO), funs(case_when(. == 5 ~ "technocratic"))) %>%
  dplyr::rename(Govt = SYSTEMTECHNO)

religionrisk <- codedmodule2%>%
  group_by(SYSTEMRELIGION)%>%
  filter(SYSTEMRELIGION == 5)%>%
  summarize_at(vars(starts_with(c("RISKY"))), list(~mean(., na.rm = TRUE), ~median(., na.rm = TRUE), ~sd(.,na.rm = TRUE),~var(.,na.rm = TRUE), ~n())) %>%
  #melt to long format
  gather(key = "technology", value = "summary", Risky_Hydro_mean, Risky_Solar_mean, Risky_Wind_mean, Risky_Nuclear_mean, Risky_Coal_mean, Risky_Gas_mean, Risky_Oil_mean, Risky_Hydro_sd, Risky_Solar_sd, Risky_Wind_sd, Risky_Nuclear_sd, Risky_Coal_sd, Risky_Gas_sd, Risky_Oil_sd) %>%
  select(SYSTEMRELIGION, technology, summary) %>%
  # separate risky from variable suffix
  separate(technology, c("Risky", "var"), extra = "merge", fill = "left") %>%
  #separate mean from variable prefix
  separate(var, c("technology", "meansd")) %>%
  # spread summary values back to wide form
  spread(meansd,summary) %>%
  #clean up
  select(-Risky)%>%
  arrange(mean)%>%
  mutate_at(vars(SYSTEMRELIGION), funs(case_when(. == 5 ~ "religious"))) %>%
  dplyr::rename(Govt = SYSTEMRELIGION)

totalrisk <- codedmodule2%>%
  group_by(SYSTEMTOTAL)%>%
  filter(SYSTEMTOTAL == 5)%>%
  summarize_at(vars(starts_with(c("RISKY"))), list(~mean(., na.rm = TRUE), ~median(., na.rm = TRUE), ~sd(.,na.rm = TRUE),~var(.,na.rm = TRUE), ~n())) %>%
  #melt to long format
  gather(key = "technology", value = "summary", Risky_Hydro_mean, Risky_Solar_mean, Risky_Wind_mean, Risky_Nuclear_mean, Risky_Coal_mean, Risky_Gas_mean, Risky_Oil_mean, Risky_Hydro_sd, Risky_Solar_sd, Risky_Wind_sd, Risky_Nuclear_sd, Risky_Coal_sd, Risky_Gas_sd, Risky_Oil_sd) %>%
  select(SYSTEMTOTAL, technology, summary) %>%
  # separate risky from variable suffix
  separate(technology, c("Risky", "var"), extra = "merge", fill = "left") %>%
  #separate mean from variable prefix
  separate(var, c("technology", "meansd")) %>%
  # spread summary values back to wide form
  spread(meansd,summary) %>%
  #clean up
  select(-Risky)%>%
  arrange(mean)%>%
  mutate_at(vars(SYSTEMTOTAL), funs(case_when(. == 5 ~ "totalitarian"))) %>%
  dplyr::rename(Govt = SYSTEMTOTAL)
```



```{r, echo=FALSE}

df1 <- full_join(religionrisk, totalrisk)
df2 <- full_join(demorisk, techrisk)
govtgraph <- full_join(df1, df2) %>%
  group_by(technology)


ggplot(govtgraph, aes(x = technology, y= mean, group = Govt))+
  geom_line(aes(colour = Govt, line = Govt)) 
  #ylim(0,4)
  #scale_color_manual(values = c("darkred", "steelblue"))
  

```






```{r, echo=FALSE}

ecopolscalescores <- codedmodule2 %>%
  select(starts_with(c("Risky","SYSTEMDEMO","SYSTEMRELIGION","SYSTEMTECHNO","SYSTEMTOTAL","WEALTHLIM","MECHANISATION","DECISIONDECEN","DECISIONCEN","INDUSTRYLARGE","INDUSTRYSMALL","ECONOMYGLOBAL","ECONOMYLOCAL", "ENVOVERDEV","DEVOVERENV","OWNERPVT","OWNERNOREG","OWNERPUB", "OWNERREG")))%>%
  rowwise()%>%
  dplyr::mutate(Pro_decentralisation = mean(c_across("DECISIONDECEN":"DECISIONCEN")))%>%
   dplyr::mutate(Pro_largescale = mean(c_across("INDUSTRYLARGE":"INDUSTRYSMALL")))%>%
   dplyr::mutate(Pro_global = mean(c_across("ECONOMYGLOBAL":"ECONOMYLOCAL")))%>%
   dplyr::mutate(Pro_ecogrowth = mean(c_across("ENVOVERDEV":"DEVOVERENV")))%>%
   dplyr::mutate(Pro_private = mean(c_across("OWNERPVT":"OWNERREG")))%>%
  dplyr::select(!c("DECISIONDECEN","DECISIONCEN", "INDUSTRYLARGE","INDUSTRYSMALL","ECONOMYGLOBAL", "ECONOMYLOCAL","ENVOVERDEV",     "DEVOVERENV","OWNERPVT","OWNERNOREG","OWNERPUB", "OWNERREG")) %>%
    na.omit()

ggplot(ecopolscalescores, aes(Pro_decentralisation, Risky_Hydro))+
  geom_point()




```


